import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Hero from "@/components/Hero/Hero";
import Features from "@/components/Features/Features";
import Plans from "@/components/Plans/Plans";
import Network from "@/components/Network/Network";
import Testimonial from "@/components/Testimonial/Testimonial";
import Subscribe from "@/components/Subscribe/Subscribe";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
	return (
		<>
			<Head>
				<title>Lasles VPN</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main>
				<Hero />
				{/* <Features /> */}
				<Plans />
				{/* <Network /> */}
				<Testimonial />
				<Subscribe />
			</main>
		</>
	);
}
